name: Deploy to Productservice (ECS Fargate)

on:
  push:
    branches: [main]

env:
  AWS_REGION:      us-east-1
#  ENVIRONMENT:     prod
  ECR_PRODUCT:     shopms-prod-product-service
#  ECR_ORDER:       shopms-prod-order-service
#  ECR_FRONTEND:    shopms-prod-frontend
#  ECS_CLUSTER:     shopms-prod-cluster
#  PRODUCT_SVC:     shopms-prod-product-service
#  ORDER_SVC:       shopms-prod-order-service
#  FRONTEND_SVC:    shopms-prod-frontend

jobs:
  build-product:
    name: Build Product Service
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region:            ${{ env.AWS_REGION }}
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build & Push Product Service
        id: build
        working-directory: product-service
        env:
          REGISTRY:  ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=$REGISTRY/$ECR_PRODUCT:$IMAGE_TAG
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          docker tag $IMAGE_URI $REGISTRY/$ECR_PRODUCT:latest
          docker push $REGISTRY/$ECR_PRODUCT:latest
          echo "image=$IMAGE_URI" >> $GITHUB_OUTPUT